// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHEJ4MHXYgTLrm_xSQmrKZyCNpDVUky7s',
    appId: '1:688904260688:web:421d18e774915c824d1555',
    messagingSenderId: '688904260688',
    projectId: 'ongeachartapp',
    authDomain: 'ongeachartapp.firebaseapp.com',
    storageBucket: 'ongeachartapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB51jV2kIPUNoSQLd3kdIkgAxa1qE-sG00',
    appId: '1:688904260688:android:b64481c6c5d397834d1555',
    messagingSenderId: '688904260688',
    projectId: 'ongeachartapp',
    storageBucket: 'ongeachartapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAln_aGndKk5G7CKSz-VVeEIVFSggXPKDo',
    appId: '1:688904260688:ios:5a5e472f5c2157654d1555',
    messagingSenderId: '688904260688',
    projectId: 'ongeachartapp',
    storageBucket: 'ongeachartapp.appspot.com',
    iosBundleId: 'com.example.ongeaChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAln_aGndKk5G7CKSz-VVeEIVFSggXPKDo',
    appId: '1:688904260688:ios:5a5e472f5c2157654d1555',
    messagingSenderId: '688904260688',
    projectId: 'ongeachartapp',
    storageBucket: 'ongeachartapp.appspot.com',
    iosBundleId: 'com.example.ongeaChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHEJ4MHXYgTLrm_xSQmrKZyCNpDVUky7s',
    appId: '1:688904260688:web:bfbf5c4ffe34380f4d1555',
    messagingSenderId: '688904260688',
    projectId: 'ongeachartapp',
    authDomain: 'ongeachartapp.firebaseapp.com',
    storageBucket: 'ongeachartapp.appspot.com',
  );
}
